import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/shared/navbar"; 
import Footer from "@/components/shared/footer";
import WhatsAppButton from "@/components/shared/whatsapp-button"; 
import FaqSection from "@/components/section/faq";
import {
  ClerkProvider,
  
} from '@clerk/nextjs'
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-slate-50 text-slate-900 min-h-screen flex flex-col">
          {/* Loading Bar - Akan muncul setiap berpindah halaman */}
          <NextTopLoader 
            color="#2563eb" // Blue-600
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2563eb,0 0 5px #2563eb"
            zIndex={1600}
            showAtBottom={false}
          />

          <Navbar />
          
          {/* Main Content */}
          <main className="flex-grow">
            {children}
          </main>

          <FaqSection />
          <Footer />
          <WhatsAppButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
